services:
  backend:
    build:
      context: ../my-home-backend
    container_name: my-home-backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - ./config.json:/config.json:ro

  web:
    build:
      context: ../my-home-web
    container_name: my-home-web
    expose:
      - "8081"
    networks:
      - app-network

  nginx:
    image: nginx:1.25-alpine
    container_name: my-home-nginx
    depends_on:
      - web
      - backend
    ports:
      - "8082:8082"
    expose:
      - "8082"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
